/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedClaimsRouteImport } from './routes/_authenticated/claims'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedItemsRouteImport } from './routes/_authenticated/items'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as NotesTokenRouteImport } from './routes/notes.$token'
import { Route as QuotesTokenRouteImport } from './routes/quotes.$token'
import { Route as AuthenticatedApprovalsNoteIdRouteImport } from './routes/_authenticated/approvals_.$noteId'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers_.$customerId'
import { Route as AuthenticatedDeliveryNotesNoteIdRouteImport } from './routes/_authenticated/delivery-notes.$noteId'
import { Route as AuthenticatedItemsItemIdRouteImport } from './routes/_authenticated/items_.$itemId'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders_.$orderId'
import { Route as AuthenticatedQuotationsQuotationIdRouteImport } from './routes/_authenticated/quotations_.$quotationId'
import { Route as AuthenticatedRetentionNotesNoteIdRouteImport } from './routes/_authenticated/retention-notes.$noteId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClaimsRoute = AuthenticatedClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemsRoute = AuthenticatedItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const NotesTokenRoute = NotesTokenRouteImport.update({
  id: '/notes/$token',
  path: '/notes/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesTokenRoute = QuotesTokenRouteImport.update({
  id: '/quotes/$token',
  path: '/quotes/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovalsNoteIdRoute =
  AuthenticatedApprovalsNoteIdRouteImport.update({
    id: '/approvals_/$noteId',
    path: '/approvals/$noteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers_/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeliveryNotesNoteIdRoute =
  AuthenticatedDeliveryNotesNoteIdRouteImport.update({
    id: '/delivery-notes/$noteId',
    path: '/delivery-notes/$noteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsItemIdRoute =
  AuthenticatedItemsItemIdRouteImport.update({
    id: '/items_/$itemId',
    path: '/items/$itemId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders_/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuotationsQuotationIdRoute =
  AuthenticatedQuotationsQuotationIdRouteImport.update({
    id: '/quotations_/$quotationId',
    path: '/quotations/$quotationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRetentionNotesNoteIdRoute =
  AuthenticatedRetentionNotesNoteIdRouteImport.update({
    id: '/retention-notes/$noteId',
    path: '/retention-notes/$noteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/items': typeof AuthenticatedItemsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/notes/$token': typeof NotesTokenRoute
  '/quotes/$token': typeof QuotesTokenRoute
  '/approvals/$noteId': typeof AuthenticatedApprovalsNoteIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/delivery-notes/$noteId': typeof AuthenticatedDeliveryNotesNoteIdRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/quotations/$quotationId': typeof AuthenticatedQuotationsQuotationIdRoute
  '/retention-notes/$noteId': typeof AuthenticatedRetentionNotesNoteIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/items': typeof AuthenticatedItemsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/notes/$token': typeof NotesTokenRoute
  '/quotes/$token': typeof QuotesTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/approvals/$noteId': typeof AuthenticatedApprovalsNoteIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/delivery-notes/$noteId': typeof AuthenticatedDeliveryNotesNoteIdRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/quotations/$quotationId': typeof AuthenticatedQuotationsQuotationIdRoute
  '/retention-notes/$noteId': typeof AuthenticatedRetentionNotesNoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/claims': typeof AuthenticatedClaimsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/items': typeof AuthenticatedItemsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/notes/$token': typeof NotesTokenRoute
  '/quotes/$token': typeof QuotesTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/approvals_/$noteId': typeof AuthenticatedApprovalsNoteIdRoute
  '/_authenticated/customers_/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/delivery-notes/$noteId': typeof AuthenticatedDeliveryNotesNoteIdRoute
  '/_authenticated/items_/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/_authenticated/orders_/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/quotations_/$quotationId': typeof AuthenticatedQuotationsQuotationIdRoute
  '/_authenticated/retention-notes/$noteId': typeof AuthenticatedRetentionNotesNoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/approvals'
    | '/claims'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/items'
    | '/orders'
    | '/quotations'
    | '/stock'
    | '/notes/$token'
    | '/quotes/$token'
    | '/approvals/$noteId'
    | '/customers/$customerId'
    | '/delivery-notes/$noteId'
    | '/items/$itemId'
    | '/orders/$orderId'
    | '/quotations/$quotationId'
    | '/retention-notes/$noteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/approvals'
    | '/claims'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/items'
    | '/orders'
    | '/quotations'
    | '/stock'
    | '/notes/$token'
    | '/quotes/$token'
    | '/'
    | '/approvals/$noteId'
    | '/customers/$customerId'
    | '/delivery-notes/$noteId'
    | '/items/$itemId'
    | '/orders/$orderId'
    | '/quotations/$quotationId'
    | '/retention-notes/$noteId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/approvals'
    | '/_authenticated/claims'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/items'
    | '/_authenticated/orders'
    | '/_authenticated/quotations'
    | '/_authenticated/stock'
    | '/notes/$token'
    | '/quotes/$token'
    | '/_authenticated/'
    | '/_authenticated/approvals_/$noteId'
    | '/_authenticated/customers_/$customerId'
    | '/_authenticated/delivery-notes/$noteId'
    | '/_authenticated/items_/$itemId'
    | '/_authenticated/orders_/$orderId'
    | '/_authenticated/quotations_/$quotationId'
    | '/_authenticated/retention-notes/$noteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotesTokenRoute: typeof NotesTokenRoute
  QuotesTokenRoute: typeof QuotesTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/claims': {
      id: '/_authenticated/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof AuthenticatedClaimsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items': {
      id: '/_authenticated/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthenticatedItemsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/notes/$token': {
      id: '/notes/$token'
      path: '/notes/$token'
      fullPath: '/notes/$token'
      preLoaderRoute: typeof NotesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/$token': {
      id: '/quotes/$token'
      path: '/quotes/$token'
      fullPath: '/quotes/$token'
      preLoaderRoute: typeof QuotesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals_/$noteId': {
      id: '/_authenticated/approvals_/$noteId'
      path: '/approvals/$noteId'
      fullPath: '/approvals/$noteId'
      preLoaderRoute: typeof AuthenticatedApprovalsNoteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers_/$customerId': {
      id: '/_authenticated/customers_/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/delivery-notes/$noteId': {
      id: '/_authenticated/delivery-notes/$noteId'
      path: '/delivery-notes/$noteId'
      fullPath: '/delivery-notes/$noteId'
      preLoaderRoute: typeof AuthenticatedDeliveryNotesNoteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items_/$itemId': {
      id: '/_authenticated/items_/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof AuthenticatedItemsItemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders_/$orderId': {
      id: '/_authenticated/orders_/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quotations_/$quotationId': {
      id: '/_authenticated/quotations_/$quotationId'
      path: '/quotations/$quotationId'
      fullPath: '/quotations/$quotationId'
      preLoaderRoute: typeof AuthenticatedQuotationsQuotationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/retention-notes/$noteId': {
      id: '/_authenticated/retention-notes/$noteId'
      path: '/retention-notes/$noteId'
      fullPath: '/retention-notes/$noteId'
      preLoaderRoute: typeof AuthenticatedRetentionNotesNoteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedClaimsRoute: typeof AuthenticatedClaimsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedItemsRoute: typeof AuthenticatedItemsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedApprovalsNoteIdRoute: typeof AuthenticatedApprovalsNoteIdRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedDeliveryNotesNoteIdRoute: typeof AuthenticatedDeliveryNotesNoteIdRoute
  AuthenticatedItemsItemIdRoute: typeof AuthenticatedItemsItemIdRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
  AuthenticatedQuotationsQuotationIdRoute: typeof AuthenticatedQuotationsQuotationIdRoute
  AuthenticatedRetentionNotesNoteIdRoute: typeof AuthenticatedRetentionNotesNoteIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedClaimsRoute: AuthenticatedClaimsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedItemsRoute: AuthenticatedItemsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedApprovalsNoteIdRoute: AuthenticatedApprovalsNoteIdRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedDeliveryNotesNoteIdRoute: AuthenticatedDeliveryNotesNoteIdRoute,
  AuthenticatedItemsItemIdRoute: AuthenticatedItemsItemIdRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
  AuthenticatedQuotationsQuotationIdRoute:
    AuthenticatedQuotationsQuotationIdRoute,
  AuthenticatedRetentionNotesNoteIdRoute:
    AuthenticatedRetentionNotesNoteIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  NotesTokenRoute: NotesTokenRoute,
  QuotesTokenRoute: QuotesTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
