/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedItemsRouteImport } from './routes/_authenticated/items'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'
import { Route as AuthenticatedItemsItemIdRouteImport } from './routes/_authenticated/items.$itemId'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as AuthenticatedQuotationsQuotationIdRouteImport } from './routes/_authenticated/quotations.$quotationId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemsRoute = AuthenticatedItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedItemsItemIdRoute =
  AuthenticatedItemsItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => AuthenticatedItemsRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedOrdersRoute,
  } as any)
const AuthenticatedQuotationsQuotationIdRoute =
  AuthenticatedQuotationsQuotationIdRouteImport.update({
    id: '/$quotationId',
    path: '/$quotationId',
    getParentRoute: () => AuthenticatedQuotationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/items': typeof AuthenticatedItemsRouteWithChildren
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/quotations/$quotationId': typeof AuthenticatedQuotationsQuotationIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/items': typeof AuthenticatedItemsRouteWithChildren
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/quotations/$quotationId': typeof AuthenticatedQuotationsQuotationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/items': typeof AuthenticatedItemsRouteWithChildren
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/items/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/quotations/$quotationId': typeof AuthenticatedQuotationsQuotationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/customers'
    | '/items'
    | '/orders'
    | '/quotations'
    | '/customers/$customerId'
    | '/items/$itemId'
    | '/orders/$orderId'
    | '/quotations/$quotationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/customers'
    | '/items'
    | '/orders'
    | '/quotations'
    | '/'
    | '/customers/$customerId'
    | '/items/$itemId'
    | '/orders/$orderId'
    | '/quotations/$quotationId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/customers'
    | '/_authenticated/items'
    | '/_authenticated/orders'
    | '/_authenticated/quotations'
    | '/_authenticated/'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/items/$itemId'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/quotations/$quotationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items': {
      id: '/_authenticated/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthenticatedItemsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/items/$itemId': {
      id: '/_authenticated/items/$itemId'
      path: '/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof AuthenticatedItemsItemIdRouteImport
      parentRoute: typeof AuthenticatedItemsRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/quotations/$quotationId': {
      id: '/_authenticated/quotations/$quotationId'
      path: '/$quotationId'
      fullPath: '/quotations/$quotationId'
      preLoaderRoute: typeof AuthenticatedQuotationsQuotationIdRouteImport
      parentRoute: typeof AuthenticatedQuotationsRoute
    }
  }
}

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersCustomerIdRoute:
      AuthenticatedCustomersCustomerIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedItemsRouteChildren {
  AuthenticatedItemsItemIdRoute: typeof AuthenticatedItemsItemIdRoute
}

const AuthenticatedItemsRouteChildren: AuthenticatedItemsRouteChildren = {
  AuthenticatedItemsItemIdRoute: AuthenticatedItemsItemIdRoute,
}

const AuthenticatedItemsRouteWithChildren =
  AuthenticatedItemsRoute._addFileChildren(AuthenticatedItemsRouteChildren)

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedQuotationsRouteChildren {
  AuthenticatedQuotationsQuotationIdRoute: typeof AuthenticatedQuotationsQuotationIdRoute
}

const AuthenticatedQuotationsRouteChildren: AuthenticatedQuotationsRouteChildren =
  {
    AuthenticatedQuotationsQuotationIdRoute:
      AuthenticatedQuotationsQuotationIdRoute,
  }

const AuthenticatedQuotationsRouteWithChildren =
  AuthenticatedQuotationsRoute._addFileChildren(
    AuthenticatedQuotationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedItemsRoute: typeof AuthenticatedItemsRouteWithChildren
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedItemsRoute: AuthenticatedItemsRouteWithChildren,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
