/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedItemsRouteImport } from './routes/_authenticated/items'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as NotesTokenRouteImport } from './routes/notes.$token'
import { Route as AuthenticatedApprovalsNoteIdRouteImport } from './routes/_authenticated/approvals.$noteId'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'
import { Route as AuthenticatedDeliveryNotesNoteIdRouteImport } from './routes/_authenticated/delivery-notes.$noteId'
import { Route as AuthenticatedItemsItemIdRouteImport } from './routes/_authenticated/items.$itemId'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as AuthenticatedQuotationsQuotationIdRouteImport } from './routes/_authenticated/quotations.$quotationId'
import { Route as AuthenticatedRetentionNotesNoteIdRouteImport } from './routes/_authenticated/retention-notes.$noteId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemsRoute = AuthenticatedItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const NotesTokenRoute = NotesTokenRouteImport.update({
  id: '/notes/$token',
  path: '/notes/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovalsNoteIdRoute =
  AuthenticatedApprovalsNoteIdRouteImport.update({
    id: '/$noteId',
    path: '/$noteId',
    getParentRoute: () => AuthenticatedApprovalsRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedDeliveryNotesNoteIdRoute =
  AuthenticatedDeliveryNotesNoteIdRouteImport.update({
    id: '/delivery-notes/$noteId',
    path: '/delivery-notes/$noteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsItemIdRoute =
  AuthenticatedItemsItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => AuthenticatedItemsRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedOrdersRoute,
  } as any)
const AuthenticatedQuotationsQuotationIdRoute =
  AuthenticatedQuotationsQuotationIdRouteImport.update({
    id: '/$quotationId',
    path: '/$quotationId',
    getParentRoute: () => AuthenticatedQuotationsRoute,
  } as any)
const AuthenticatedRetentionNotesNoteIdRoute =
  AuthenticatedRetentionNotesNoteIdRouteImport.update({
    id: '/retention-notes/$noteId',
    path: '/retention-notes/$noteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AuthenticatedApprovalsRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/finance': typeof AuthenticatedFinanceRoute
  '/items': typeof AuthenticatedItemsRouteWithChildren
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/stock': typeof AuthenticatedStockRoute
  '/notes/$token': typeof NotesTokenRoute
  '/approvals/$noteId': typeof AuthenticatedApprovalsNoteIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/delivery-notes/$noteId': typeof AuthenticatedDeliveryNotesNoteIdRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/quotations/$quotationId': typeof AuthenticatedQuotationsQuotationIdRoute
  '/retention-notes/$noteId': typeof AuthenticatedRetentionNotesNoteIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/approvals': typeof AuthenticatedApprovalsRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/finance': typeof AuthenticatedFinanceRoute
  '/items': typeof AuthenticatedItemsRouteWithChildren
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/stock': typeof AuthenticatedStockRoute
  '/notes/$token': typeof NotesTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/approvals/$noteId': typeof AuthenticatedApprovalsNoteIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/delivery-notes/$noteId': typeof AuthenticatedDeliveryNotesNoteIdRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/quotations/$quotationId': typeof AuthenticatedQuotationsQuotationIdRoute
  '/retention-notes/$noteId': typeof AuthenticatedRetentionNotesNoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRouteWithChildren
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/items': typeof AuthenticatedItemsRouteWithChildren
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/notes/$token': typeof NotesTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/approvals/$noteId': typeof AuthenticatedApprovalsNoteIdRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/delivery-notes/$noteId': typeof AuthenticatedDeliveryNotesNoteIdRoute
  '/_authenticated/items/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/quotations/$quotationId': typeof AuthenticatedQuotationsQuotationIdRoute
  '/_authenticated/retention-notes/$noteId': typeof AuthenticatedRetentionNotesNoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/approvals'
    | '/customers'
    | '/finance'
    | '/items'
    | '/orders'
    | '/quotations'
    | '/stock'
    | '/notes/$token'
    | '/approvals/$noteId'
    | '/customers/$customerId'
    | '/delivery-notes/$noteId'
    | '/items/$itemId'
    | '/orders/$orderId'
    | '/quotations/$quotationId'
    | '/retention-notes/$noteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/approvals'
    | '/customers'
    | '/finance'
    | '/items'
    | '/orders'
    | '/quotations'
    | '/stock'
    | '/notes/$token'
    | '/'
    | '/approvals/$noteId'
    | '/customers/$customerId'
    | '/delivery-notes/$noteId'
    | '/items/$itemId'
    | '/orders/$orderId'
    | '/quotations/$quotationId'
    | '/retention-notes/$noteId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/approvals'
    | '/_authenticated/customers'
    | '/_authenticated/finance'
    | '/_authenticated/items'
    | '/_authenticated/orders'
    | '/_authenticated/quotations'
    | '/_authenticated/stock'
    | '/notes/$token'
    | '/_authenticated/'
    | '/_authenticated/approvals/$noteId'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/delivery-notes/$noteId'
    | '/_authenticated/items/$itemId'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/quotations/$quotationId'
    | '/_authenticated/retention-notes/$noteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotesTokenRoute: typeof NotesTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items': {
      id: '/_authenticated/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthenticatedItemsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/notes/$token': {
      id: '/notes/$token'
      path: '/notes/$token'
      fullPath: '/notes/$token'
      preLoaderRoute: typeof NotesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals/$noteId': {
      id: '/_authenticated/approvals/$noteId'
      path: '/$noteId'
      fullPath: '/approvals/$noteId'
      preLoaderRoute: typeof AuthenticatedApprovalsNoteIdRouteImport
      parentRoute: typeof AuthenticatedApprovalsRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/delivery-notes/$noteId': {
      id: '/_authenticated/delivery-notes/$noteId'
      path: '/delivery-notes/$noteId'
      fullPath: '/delivery-notes/$noteId'
      preLoaderRoute: typeof AuthenticatedDeliveryNotesNoteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/$itemId': {
      id: '/_authenticated/items/$itemId'
      path: '/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof AuthenticatedItemsItemIdRouteImport
      parentRoute: typeof AuthenticatedItemsRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/quotations/$quotationId': {
      id: '/_authenticated/quotations/$quotationId'
      path: '/$quotationId'
      fullPath: '/quotations/$quotationId'
      preLoaderRoute: typeof AuthenticatedQuotationsQuotationIdRouteImport
      parentRoute: typeof AuthenticatedQuotationsRoute
    }
    '/_authenticated/retention-notes/$noteId': {
      id: '/_authenticated/retention-notes/$noteId'
      path: '/retention-notes/$noteId'
      fullPath: '/retention-notes/$noteId'
      preLoaderRoute: typeof AuthenticatedRetentionNotesNoteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedApprovalsRouteChildren {
  AuthenticatedApprovalsNoteIdRoute: typeof AuthenticatedApprovalsNoteIdRoute
}

const AuthenticatedApprovalsRouteChildren: AuthenticatedApprovalsRouteChildren =
  {
    AuthenticatedApprovalsNoteIdRoute: AuthenticatedApprovalsNoteIdRoute,
  }

const AuthenticatedApprovalsRouteWithChildren =
  AuthenticatedApprovalsRoute._addFileChildren(
    AuthenticatedApprovalsRouteChildren,
  )

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersCustomerIdRoute:
      AuthenticatedCustomersCustomerIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedItemsRouteChildren {
  AuthenticatedItemsItemIdRoute: typeof AuthenticatedItemsItemIdRoute
}

const AuthenticatedItemsRouteChildren: AuthenticatedItemsRouteChildren = {
  AuthenticatedItemsItemIdRoute: AuthenticatedItemsItemIdRoute,
}

const AuthenticatedItemsRouteWithChildren =
  AuthenticatedItemsRoute._addFileChildren(AuthenticatedItemsRouteChildren)

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedQuotationsRouteChildren {
  AuthenticatedQuotationsQuotationIdRoute: typeof AuthenticatedQuotationsQuotationIdRoute
}

const AuthenticatedQuotationsRouteChildren: AuthenticatedQuotationsRouteChildren =
  {
    AuthenticatedQuotationsQuotationIdRoute:
      AuthenticatedQuotationsQuotationIdRoute,
  }

const AuthenticatedQuotationsRouteWithChildren =
  AuthenticatedQuotationsRoute._addFileChildren(
    AuthenticatedQuotationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRouteWithChildren
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedItemsRoute: typeof AuthenticatedItemsRouteWithChildren
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRouteWithChildren
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDeliveryNotesNoteIdRoute: typeof AuthenticatedDeliveryNotesNoteIdRoute
  AuthenticatedRetentionNotesNoteIdRoute: typeof AuthenticatedRetentionNotesNoteIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRouteWithChildren,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedItemsRoute: AuthenticatedItemsRouteWithChildren,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRouteWithChildren,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDeliveryNotesNoteIdRoute: AuthenticatedDeliveryNotesNoteIdRoute,
  AuthenticatedRetentionNotesNoteIdRoute:
    AuthenticatedRetentionNotesNoteIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  NotesTokenRoute: NotesTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
